export const ADD_ARTICLE = "ADD_ARTICLE";
export const BUILDER_MODE_REQUESTED = "BUILDER_MODE_REQUESTED";
export const BUILDER_MODE_SUCCESS = "BUILDER_MODE_SUCCESS";
export const BUILDER_MODE_FAILURE = "BUILDER_MODE_FAILURE";

